### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by linkenmin** [turuslan/HackTimer#1]
@line 51:
callback.call (window);

It seldom happens to some people, I wonder why?
And it's a great job, thank you very much.

**Comment by turuslan** [comment]
Thanks for reporting. 
My code does not check if your callback is valid function before calling it.
So if callback you pass to setInterval and setTimeout are not functions my code will throw error.

I will fix it as soon as possible.

**Comment by turuslan** [comment]
I have fixed it.
Check if it is working as expected, please.

**Comment by linkenmin** [comment]
Ok, I will keep monitoring it.
Thank you again for your great work!
