### ISSUE TITLE
Google Chrome

### ISSUE THREAD

**Issue by barsteadr** [turuslan/HackTimer#24]
Unfortunately, it looks like Google may have patched around this **wonderful** webworker hack. (This hack fails in Google Chrome `54.0.2840.71`). Our team is investigating but we thought we'd submit an issue here too. If we discover the solution we'll be more than happy to contribute to this work.

**Comment by turuslan** [comment]
Thanks

**Comment by JonMcPherson** [comment]
I made an SO question on this same topic with a demo.
[http://stackoverflow.com/questions/40475238/web-workers-in-chrome-v54-run-twice-as-slow-when-running-in-an-inactive-tab](http://stackoverflow.com/questions/40475238/web-workers-in-chrome-v54-run-twice-as-slow-when-running-in-an-inactive-tab)

**Comment by MrStofkat** [comment]
This hack looked like a lifesaver for me, but indeed doesn't work in the current version of Chrome. Is this issue likely to be fixed or has the patch made the workaround completely impossible?  Would like to know if I'd have to rewrite my code to a worker. Thanks!

**Comment by erichummel** [comment]
yes, unfortunately this doesn't work anymore. it _was_ a lifesaver when it did, bummer. I'm going to have to come up with some other solution for this problem, as we've got an SPA that very much relies on timers, and get's all screwy when the tab is backgrounded for a while.

**Comment by jasongrishkoff** [comment]
Any recommended solutions?  Also working with an audio app.

**Comment by dskvr** [comment]
I'm using latest version of Chrome and it's working perfectly.

**Comment by JonMcPherson** [comment]
@dskvr Yes it seems the throttling for inactive tabs was removed!

**Comment by jasongrishkoff** [comment]
Yeah, hasn't been a problem for me in a while.
