### ISSUE TITLE
publish on bower

### ISSUE THREAD

**Issue by seiyria** [turuslan/HackTimer#9]
much like having this on npm, having this on bower would be great. along with this, having a tag would be awesome, since bower works on tags.

**Comment by turuslan** [comment]
I have published it on bower
[readme.md - bower](https://github.com/turuslan/HackTimer#bower)
Please check if it works as expected

**Comment by seiyria** [comment]
It does, but I'm not sure why you have separate registries for it -- most folks only use that in a corporate setting.

**Comment by seiyria** [comment]
Thanks all the same!
